version: "3.8"

services:
  strongswan:
    build: .
    container_name: strongswan
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    networks:
      mynet:
        ipv4_address: ${STRONGSWAN_IP}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_CIDR}
